import {
  Geist,
  Geist_Mono,
  Inconsolata,
  Noto_Sans_Pahawh_Hmong,
} from 'next/font/google';
import './globals.css';
import { Pointer } from '@/components/ui/pointer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const inconsolata = Inconsolata({
  variable: '--font-inconsolata',
  subsets: ['latin'],
  weight: '400',
});

const nanoSansPahwhHmong = Noto_Sans_Pahawh_Hmong({
  variable: '--font-nano-sans',
  subsets: ['latin'],
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} ${inconsolata.variable} ${nanoSansPahwhHmong.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <Pointer />
        {children}
      </body>
    </html>
  );
}
