import { Arimo } from 'next/font/google';
import './globals.css';
import CustomCursor from '@/components/CustomCursor';

const arimo = Arimo({
  variable: '--font-arimo',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${arimo.className} h-full antialiased`}>
      <body className='min-h-full flex flex-col bg-neutral-950 overflow-x-hidden'>
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
